### ISSUE TITLE
1MB limit

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#18]
Does the 1MB limit still hold true? It seems awfully small for a swagger file, many I've worked with are around 2-3MB. I understood the low limit when this was first launched, but three years later - is this still the hard limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9659a345-1116-5020-4300-386f3a591c2e
* Version Independent ID: e2a3861f-d3d5-f542-28db-1897d4c7feb0
* Content: [Create a custom connector from an OpenAPI definition](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition)
* Content Source: [docs/custom-connectors/define-openapi-definition.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-openapi-definition.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by aarroonn789** [comment]
I would also like to see this size increased. I would like to use MS Logic Apps to automate some tasks in a software suite I use, but the Swagger file is 1.5MB in size.

**Comment by healeyio** [comment]
Please!

**Comment by dougelliott** [comment]
Hey all - thanks for the feedback with this! We're discussing this internally and we'll circle back once we've got some more information to share.

**Comment by dougelliott** [comment]
Hey Everyone,

Update on this: The limit is still 1 MB at this time, so the documentation remains correct. Since the documentation is correct, I will go ahead and close this issue. But please do [provide feedback](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) on the file size limit if you would like. Following these steps will ensure that the feedback lands in the right place for our tracking and enable additional community discussion on the idea.

**Comment by aarroonn789** [comment]
Thanks for the guidance, Doug.

I have created a [feature request](https://feedback.azure.com/forums/287593-logic-apps/suggestions/40476874-increase-file-size-limit-for-openapi-definition-im) on the Azure Logic Apps user feedback page.
