### ISSUE TITLE
Custom Connectors with OAuth authentication expires after 1hour

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#349]
We have a Custom Connector that we use for Teams Integration. We Setup the OAuth Security and provided the values as documented. Once the connection is created for custom connector it expires after 1 hr. or so. But we don't know that connection is expired until we run the flow.

Is there a way to remove this expiration limit or refresh the connection before expiration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd4ed455-8e17-4699-da0f-c7dc01d72c12
* Version Independent ID: a1662685-6c0b-d920-f6d8-929b176fbe6c
* Content: [Create a custom connector from a Postman collection](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-postman-collection)
* Content Source: [docs/custom-connectors/define-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Hi @gregdegruy ! Thank you for asking this question and raising this issue. This may have to do with the refresh URL. I suggest that you post your custom connector development question here so that an engineer can help you resolve this: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/ConnectorDevelopment
