### ISSUE TITLE
Excel Desktop Connector Deprecated

### ISSUE THREAD

**Issue by chiragbh** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#41]
The information about the connector for Excel Desktop version being deprecated is not very prominent. Can we have the information highlighted and at the top as we are getting many cases in Support Team regarding connector not working with Excel Desktop version anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63dd2d5e-d90f-4654-c406-256e3e680e6d
* Version Independent ID: f2cd384b-2690-393d-3058-a363523f7d62
* Content: [Excel Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/)
* Content Source: [docs/excelonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Unfortunately on the Excel connector documentation (this issue was filed to the new Excel Online documentation), where it states that "This connector is deprecated in Power Automate. Please try using the new connectors to work with Excel files: Excel Online (Business) and Excel Online (OneDrive)." is already at the highest part of the documentation.
