### ISSUE TITLE
Specified swagger has the following errors:

### ISSUE THREAD

**Issue by OneThreeOne** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#70]
Hi there

I've tried this several times and when I get to Update the Definition point 7 I get the following message:

Specified swagger has the following errors: 'Error : paths/~1text~1analytics~1v2.0~1sentiment/post/parameters/0/schema/properties/documents/items/properties/id/default : The 'default' value is of type 'Integer', but should match the given type 'String'.

As far as I can tell this refers to either the Import From Sample section at point 6 where the code reads:
{
 "documents": [
   {
     "score": 0.0,
     "id": "string"
   }
 ],
 "errors": [
   {
     "id": "string",
     "message": "string"
   }
 ]
}

ID is designated "string" but at Update The Definition point 3 the ID default value is set at "1" which is an integer.

I edited this to be "integer" and edited the code to designate the id as "integer" also and it finally worked.

Was I just being stupid (entirely possible) or do the instructions need to be updated?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c443c1c-e4af-1f21-10b3-9c8d81abc1f1
* Version Independent ID: 9aa14809-3da3-23b3-3210-7a2e84608f04
* Content: [Create a custom connector from scratch](https://docs.microsoft.com/en-gb/connectors/custom-connectors/define-blank#feedback)
* Content Source: [docs/custom-connectors/define-blank.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-blank.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

@DougKlopfenstein can you take a look please?

**Comment by bezhan-msft** [comment]
Hello - we have tried recently and confirmed that there is no error in the documentation and that the workflow does not err out.

For further support on this please reach out to our product support through the product forums.

**Comment by alutgert** [comment]
Hi @bezhan-msft , 

I'm getting the same error. When I follow the instructions provided. The error occurs when you press "update connector" at 7 of step 3.

the error: Specified swagger has the following errors: 'Definition is not valid. Error: 'Error : paths/~1text~1analytics~1v2.0~1sentiment/post/parameters/0/schema/properties/documents/items/properties/id/default : The 'default' value is of type 'Integer', but should match the given type 'String'. '

When I just as @OneThreeOne describes  change the type of the id from string to integer the issue is solved.

**Comment by GitRomney** [comment]
Same issue here.

Error:

Specified swagger has the following errors: 'Definition is not valid.  Error: 'Error : paths/~1text~1analytics~1v2.0~1sentiment/post/parameters/0/schema/properties/documents/items/properties/id/default : The 'default' value is of type 'Integer', but should match the given type 'String'.

I tried what the above two posters suggested and it didn't work for me so I instead left the type as "string" and changed the "default" value to "one" instead of "1" and that worked. Leaving as instructed in Step 3 seems to cause us all issues.
