### ISSUE TITLE
Functions with non-scalar parameters aren't supported

### ISSUE THREAD

**Issue by ecfan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#99]
If true, please update this doc. Also reported here: 

https://github.com/MicrosoftDocs/azure-docs/issues/24266

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cd901bd-5da0-0534-1b52-6b26c7858683
* Version Independent ID: 462cbda4-4d13-a801-fe20-2abee64b84ee
* Content: [Oracle Database - Connectors](https://docs.microsoft.com/en-us/connectors/oracle/)
* Content Source: [docs/Oracle/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Oracle/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ecfan - Thanks for your feedback. Since this issue was duplicated in https://github.com/MicrosoftDocs/azure-docs/issues/24266 and was closed, we're closing it here as well. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.
